//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WEB_CLIENTE.InterfazCavali.InputService04002 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_Dim_04002_Registrar_facturas_XMLSoap", Namespace="http://cesion.org/")]
    public partial class WS_Dim_04002_Registrar_facturas_XML : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegistrarFacturasXmlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_Dim_04002_Registrar_facturas_XML() {
            this.Url = global::WEB_CLIENTE.Properties.Settings.Default.WEB_CLIENTE_WS_04002_WS_Dim_04002_Registrar_facturas_XML;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegistrarFacturasXmlCompletedEventHandler RegistrarFacturasXmlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cesion.org/RegistrarFacturasXml", RequestNamespace="http://cesion.org/", ResponseNamespace="http://cesion.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MENSAJERES_Type RegistrarFacturasXml(CABECERA_Type cabecera, Consumer_Type consumidor, ProcessDetail_Type proceso, InvoiceXML_Type[] invoice, string usuario) {
            object[] results = this.Invoke("RegistrarFacturasXml", new object[] {
                        cabecera,
                        consumidor,
                        proceso,
                        invoice,
                        usuario});
            return ((MENSAJERES_Type)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarFacturasXmlAsync(CABECERA_Type cabecera, Consumer_Type consumidor, ProcessDetail_Type proceso, InvoiceXML_Type[] invoice, string usuario) {
            this.RegistrarFacturasXmlAsync(cabecera, consumidor, proceso, invoice, usuario, null);
        }
        
        /// <remarks/>
        public void RegistrarFacturasXmlAsync(CABECERA_Type cabecera, Consumer_Type consumidor, ProcessDetail_Type proceso, InvoiceXML_Type[] invoice, string usuario, object userState) {
            if ((this.RegistrarFacturasXmlOperationCompleted == null)) {
                this.RegistrarFacturasXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarFacturasXmlOperationCompleted);
            }
            this.InvokeAsync("RegistrarFacturasXml", new object[] {
                        cabecera,
                        consumidor,
                        proceso,
                        invoice,
                        usuario}, this.RegistrarFacturasXmlOperationCompleted, userState);
        }
        
        private void OnRegistrarFacturasXmlOperationCompleted(object arg) {
            if ((this.RegistrarFacturasXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarFacturasXmlCompleted(this, new RegistrarFacturasXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/")]
    public partial class CABECERA_Type {
        
        private string cOD_SERVICIOField;
        
        private string aPP_CONSUMIDORAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_SERVICIO {
            get {
                return this.cOD_SERVICIOField;
            }
            set {
                this.cOD_SERVICIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string APP_CONSUMIDORA {
            get {
                return this.aPP_CONSUMIDORAField;
            }
            set {
                this.aPP_CONSUMIDORAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04002")]
    public partial class AddInvoiceXMLResponseDetail_Type {
        
        private string idProcesoField;
        
        private string resultCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string idProceso {
            get {
                return this.idProcesoField;
            }
            set {
                this.idProcesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04002")]
    public partial class AddInvoiceXMLResponse_Type {
        
        private AddInvoiceXMLResponseDetail_Type addInvoiceXMLResponseDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AddInvoiceXMLResponseDetail_Type addInvoiceXMLResponseDetail {
            get {
                return this.addInvoiceXMLResponseDetailField;
            }
            set {
                this.addInvoiceXMLResponseDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04002")]
    public partial class DATOSRes_Type {
        
        private AddInvoiceXMLResponse_Type addInvoiceXMLResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AddInvoiceXMLResponse_Type addInvoiceXMLResponse {
            get {
                return this.addInvoiceXMLResponseField;
            }
            set {
                this.addInvoiceXMLResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04002")]
    public partial class DETALLERes_Type {
        
        private DATOSRes_Type dATOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DATOSRes_Type DATOS {
            get {
                return this.dATOSField;
            }
            set {
                this.dATOSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb")]
    public partial class CABECERARes_Type {
        
        private string cOD_SERVICIOField;
        
        private string aPP_CONSUMIDORAField;
        
        private string tIP_RESPUESTAField;
        
        private string cOD_RESPUESTAField;
        
        private string dES_RESPUESTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_SERVICIO {
            get {
                return this.cOD_SERVICIOField;
            }
            set {
                this.cOD_SERVICIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string APP_CONSUMIDORA {
            get {
                return this.aPP_CONSUMIDORAField;
            }
            set {
                this.aPP_CONSUMIDORAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIP_RESPUESTA {
            get {
                return this.tIP_RESPUESTAField;
            }
            set {
                this.tIP_RESPUESTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_RESPUESTA {
            get {
                return this.cOD_RESPUESTAField;
            }
            set {
                this.cOD_RESPUESTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DES_RESPUESTA {
            get {
                return this.dES_RESPUESTAField;
            }
            set {
                this.dES_RESPUESTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04002")]
    public partial class INTEGRACIONRES_Type {
        
        private CABECERARes_Type cABECERAField;
        
        private DETALLERes_Type dETALLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CABECERARes_Type CABECERA {
            get {
                return this.cABECERAField;
            }
            set {
                this.cABECERAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DETALLERes_Type DETALLE {
            get {
                return this.dETALLEField;
            }
            set {
                this.dETALLEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04002")]
    public partial class MENSAJERES_Type {
        
        private INTEGRACIONRES_Type iNTEGRESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public INTEGRACIONRES_Type INTEGRES {
            get {
                return this.iNTEGRESField;
            }
            set {
                this.iNTEGRESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04002")]
    public partial class InvoiceXML_Type {
        
        private string nameField;
        
        private byte[] fileXmlField;
        
        private string additionalField1Field;
        
        private string additionalField2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] fileXml {
            get {
                return this.fileXmlField;
            }
            set {
                this.fileXmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string additionalField1 {
            get {
                return this.additionalField1Field;
            }
            set {
                this.additionalField1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string additionalField2 {
            get {
                return this.additionalField2Field;
            }
            set {
                this.additionalField2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04002")]
    public partial class ProcessDetail_Type {
        
        private string processNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string processNumber {
            get {
                return this.processNumberField;
            }
            set {
                this.processNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04002")]
    public partial class Consumer_Type {
        
        private string typeField;
        
        private string participantCodeField;
        
        private string rucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string participantCode {
            get {
                return this.participantCodeField;
            }
            set {
                this.participantCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void RegistrarFacturasXmlCompletedEventHandler(object sender, RegistrarFacturasXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarFacturasXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarFacturasXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MENSAJERES_Type Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MENSAJERES_Type)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591