//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WEB_CLIENTE.WS_TEST {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_TESTSoap", Namespace="http://cesion.org/")]
    public partial class WS_TEST : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTipoParticipanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarInfoAdiccionalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarContenidoExcelOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarExcelBDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErroresValidacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarInfoAdiccional2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoAdiccionalFacturasOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoAdiccionalCuotasOperationCompleted;
        
        private System.Threading.SendOrPostCallback VaciarTablasOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErroresValidacionVIEJOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_TEST() {
            this.Url = global::WEB_CLIENTE.Properties.Settings.Default.WEB_CLIENTE_WS_GET_TYPE_WS_TEST;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTipoParticipanteCompletedEventHandler GetTipoParticipanteCompleted;
        
        /// <remarks/>
        public event GuardarInfoAdiccionalCompletedEventHandler GuardarInfoAdiccionalCompleted;
        
        /// <remarks/>
        public event GuardarContenidoExcelCompletedEventHandler GuardarContenidoExcelCompleted;
        
        /// <remarks/>
        public event ValidarExcelBDCompletedEventHandler ValidarExcelBDCompleted;
        
        /// <remarks/>
        public event GetErroresValidacionCompletedEventHandler GetErroresValidacionCompleted;
        
        /// <remarks/>
        public event GuardarInfoAdiccional2CompletedEventHandler GuardarInfoAdiccional2Completed;
        
        /// <remarks/>
        public event GetInfoAdiccionalFacturasCompletedEventHandler GetInfoAdiccionalFacturasCompleted;
        
        /// <remarks/>
        public event GetInfoAdiccionalCuotasCompletedEventHandler GetInfoAdiccionalCuotasCompleted;
        
        /// <remarks/>
        public event VaciarTablasCompletedEventHandler VaciarTablasCompleted;
        
        /// <remarks/>
        public event GetErroresValidacionVIEJOCompletedEventHandler GetErroresValidacionVIEJOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cesion.org/GetTipoParticipante", RequestNamespace="http://cesion.org/", ResponseNamespace="http://cesion.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Parametro[] GetTipoParticipante() {
            object[] results = this.Invoke("GetTipoParticipante", new object[0]);
            return ((Parametro[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTipoParticipanteAsync() {
            this.GetTipoParticipanteAsync(null);
        }
        
        /// <remarks/>
        public void GetTipoParticipanteAsync(object userState) {
            if ((this.GetTipoParticipanteOperationCompleted == null)) {
                this.GetTipoParticipanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTipoParticipanteOperationCompleted);
            }
            this.InvokeAsync("GetTipoParticipante", new object[0], this.GetTipoParticipanteOperationCompleted, userState);
        }
        
        private void OnGetTipoParticipanteOperationCompleted(object arg) {
            if ((this.GetTipoParticipanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTipoParticipanteCompleted(this, new GetTipoParticipanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cesion.org/GuardarInfoAdiccional", RequestNamespace="http://cesion.org/", ResponseNamespace="http://cesion.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GuardarInfoAdiccional(InfoFacturas[] listaInfoFacturas, InfoCuotas[] listaInfoCuotas) {
            object[] results = this.Invoke("GuardarInfoAdiccional", new object[] {
                        listaInfoFacturas,
                        listaInfoCuotas});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarInfoAdiccionalAsync(InfoFacturas[] listaInfoFacturas, InfoCuotas[] listaInfoCuotas) {
            this.GuardarInfoAdiccionalAsync(listaInfoFacturas, listaInfoCuotas, null);
        }
        
        /// <remarks/>
        public void GuardarInfoAdiccionalAsync(InfoFacturas[] listaInfoFacturas, InfoCuotas[] listaInfoCuotas, object userState) {
            if ((this.GuardarInfoAdiccionalOperationCompleted == null)) {
                this.GuardarInfoAdiccionalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarInfoAdiccionalOperationCompleted);
            }
            this.InvokeAsync("GuardarInfoAdiccional", new object[] {
                        listaInfoFacturas,
                        listaInfoCuotas}, this.GuardarInfoAdiccionalOperationCompleted, userState);
        }
        
        private void OnGuardarInfoAdiccionalOperationCompleted(object arg) {
            if ((this.GuardarInfoAdiccionalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarInfoAdiccionalCompleted(this, new GuardarInfoAdiccionalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cesion.org/GuardarContenidoExcel", RequestNamespace="http://cesion.org/", ResponseNamespace="http://cesion.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GuardarContenidoExcel(string nombreArchivo, string nombreHoja, string rutaArchivo, string rutaArchivoCompleta, string extensionArchivo) {
            object[] results = this.Invoke("GuardarContenidoExcel", new object[] {
                        nombreArchivo,
                        nombreHoja,
                        rutaArchivo,
                        rutaArchivoCompleta,
                        extensionArchivo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarContenidoExcelAsync(string nombreArchivo, string nombreHoja, string rutaArchivo, string rutaArchivoCompleta, string extensionArchivo) {
            this.GuardarContenidoExcelAsync(nombreArchivo, nombreHoja, rutaArchivo, rutaArchivoCompleta, extensionArchivo, null);
        }
        
        /// <remarks/>
        public void GuardarContenidoExcelAsync(string nombreArchivo, string nombreHoja, string rutaArchivo, string rutaArchivoCompleta, string extensionArchivo, object userState) {
            if ((this.GuardarContenidoExcelOperationCompleted == null)) {
                this.GuardarContenidoExcelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarContenidoExcelOperationCompleted);
            }
            this.InvokeAsync("GuardarContenidoExcel", new object[] {
                        nombreArchivo,
                        nombreHoja,
                        rutaArchivo,
                        rutaArchivoCompleta,
                        extensionArchivo}, this.GuardarContenidoExcelOperationCompleted, userState);
        }
        
        private void OnGuardarContenidoExcelOperationCompleted(object arg) {
            if ((this.GuardarContenidoExcelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarContenidoExcelCompleted(this, new GuardarContenidoExcelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cesion.org/ValidarExcelBD", RequestNamespace="http://cesion.org/", ResponseNamespace="http://cesion.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ValidarExcelBD(int id_Trans) {
            object[] results = this.Invoke("ValidarExcelBD", new object[] {
                        id_Trans});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarExcelBDAsync(int id_Trans) {
            this.ValidarExcelBDAsync(id_Trans, null);
        }
        
        /// <remarks/>
        public void ValidarExcelBDAsync(int id_Trans, object userState) {
            if ((this.ValidarExcelBDOperationCompleted == null)) {
                this.ValidarExcelBDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarExcelBDOperationCompleted);
            }
            this.InvokeAsync("ValidarExcelBD", new object[] {
                        id_Trans}, this.ValidarExcelBDOperationCompleted, userState);
        }
        
        private void OnValidarExcelBDOperationCompleted(object arg) {
            if ((this.ValidarExcelBDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarExcelBDCompleted(this, new ValidarExcelBDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cesion.org/GetErroresValidacion", RequestNamespace="http://cesion.org/", ResponseNamespace="http://cesion.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetErroresValidacion(int idTrans) {
            object[] results = this.Invoke("GetErroresValidacion", new object[] {
                        idTrans});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetErroresValidacionAsync(int idTrans) {
            this.GetErroresValidacionAsync(idTrans, null);
        }
        
        /// <remarks/>
        public void GetErroresValidacionAsync(int idTrans, object userState) {
            if ((this.GetErroresValidacionOperationCompleted == null)) {
                this.GetErroresValidacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErroresValidacionOperationCompleted);
            }
            this.InvokeAsync("GetErroresValidacion", new object[] {
                        idTrans}, this.GetErroresValidacionOperationCompleted, userState);
        }
        
        private void OnGetErroresValidacionOperationCompleted(object arg) {
            if ((this.GetErroresValidacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErroresValidacionCompleted(this, new GetErroresValidacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cesion.org/GuardarInfoAdiccional2", RequestNamespace="http://cesion.org/", ResponseNamespace="http://cesion.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GuardarInfoAdiccional2(InfoFacturas[] listaInfoFacturas, InfoCuotas[] listaInfoCuotas) {
            object[] results = this.Invoke("GuardarInfoAdiccional2", new object[] {
                        listaInfoFacturas,
                        listaInfoCuotas});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarInfoAdiccional2Async(InfoFacturas[] listaInfoFacturas, InfoCuotas[] listaInfoCuotas) {
            this.GuardarInfoAdiccional2Async(listaInfoFacturas, listaInfoCuotas, null);
        }
        
        /// <remarks/>
        public void GuardarInfoAdiccional2Async(InfoFacturas[] listaInfoFacturas, InfoCuotas[] listaInfoCuotas, object userState) {
            if ((this.GuardarInfoAdiccional2OperationCompleted == null)) {
                this.GuardarInfoAdiccional2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarInfoAdiccional2OperationCompleted);
            }
            this.InvokeAsync("GuardarInfoAdiccional2", new object[] {
                        listaInfoFacturas,
                        listaInfoCuotas}, this.GuardarInfoAdiccional2OperationCompleted, userState);
        }
        
        private void OnGuardarInfoAdiccional2OperationCompleted(object arg) {
            if ((this.GuardarInfoAdiccional2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarInfoAdiccional2Completed(this, new GuardarInfoAdiccional2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cesion.org/GetInfoAdiccionalFacturas", RequestNamespace="http://cesion.org/", ResponseNamespace="http://cesion.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetInfoAdiccionalFacturas(int idTrans) {
            object[] results = this.Invoke("GetInfoAdiccionalFacturas", new object[] {
                        idTrans});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoAdiccionalFacturasAsync(int idTrans) {
            this.GetInfoAdiccionalFacturasAsync(idTrans, null);
        }
        
        /// <remarks/>
        public void GetInfoAdiccionalFacturasAsync(int idTrans, object userState) {
            if ((this.GetInfoAdiccionalFacturasOperationCompleted == null)) {
                this.GetInfoAdiccionalFacturasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoAdiccionalFacturasOperationCompleted);
            }
            this.InvokeAsync("GetInfoAdiccionalFacturas", new object[] {
                        idTrans}, this.GetInfoAdiccionalFacturasOperationCompleted, userState);
        }
        
        private void OnGetInfoAdiccionalFacturasOperationCompleted(object arg) {
            if ((this.GetInfoAdiccionalFacturasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoAdiccionalFacturasCompleted(this, new GetInfoAdiccionalFacturasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cesion.org/GetInfoAdiccionalCuotas", RequestNamespace="http://cesion.org/", ResponseNamespace="http://cesion.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetInfoAdiccionalCuotas(int idFactura) {
            object[] results = this.Invoke("GetInfoAdiccionalCuotas", new object[] {
                        idFactura});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoAdiccionalCuotasAsync(int idFactura) {
            this.GetInfoAdiccionalCuotasAsync(idFactura, null);
        }
        
        /// <remarks/>
        public void GetInfoAdiccionalCuotasAsync(int idFactura, object userState) {
            if ((this.GetInfoAdiccionalCuotasOperationCompleted == null)) {
                this.GetInfoAdiccionalCuotasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoAdiccionalCuotasOperationCompleted);
            }
            this.InvokeAsync("GetInfoAdiccionalCuotas", new object[] {
                        idFactura}, this.GetInfoAdiccionalCuotasOperationCompleted, userState);
        }
        
        private void OnGetInfoAdiccionalCuotasOperationCompleted(object arg) {
            if ((this.GetInfoAdiccionalCuotasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoAdiccionalCuotasCompleted(this, new GetInfoAdiccionalCuotasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cesion.org/VaciarTablas", RequestNamespace="http://cesion.org/", ResponseNamespace="http://cesion.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void VaciarTablas() {
            this.Invoke("VaciarTablas", new object[0]);
        }
        
        /// <remarks/>
        public void VaciarTablasAsync() {
            this.VaciarTablasAsync(null);
        }
        
        /// <remarks/>
        public void VaciarTablasAsync(object userState) {
            if ((this.VaciarTablasOperationCompleted == null)) {
                this.VaciarTablasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVaciarTablasOperationCompleted);
            }
            this.InvokeAsync("VaciarTablas", new object[0], this.VaciarTablasOperationCompleted, userState);
        }
        
        private void OnVaciarTablasOperationCompleted(object arg) {
            if ((this.VaciarTablasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VaciarTablasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cesion.org/GetErroresValidacionVIEJO", RequestNamespace="http://cesion.org/", ResponseNamespace="http://cesion.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetErroresValidacionVIEJO(int idTrans) {
            object[] results = this.Invoke("GetErroresValidacionVIEJO", new object[] {
                        idTrans});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetErroresValidacionVIEJOAsync(int idTrans) {
            this.GetErroresValidacionVIEJOAsync(idTrans, null);
        }
        
        /// <remarks/>
        public void GetErroresValidacionVIEJOAsync(int idTrans, object userState) {
            if ((this.GetErroresValidacionVIEJOOperationCompleted == null)) {
                this.GetErroresValidacionVIEJOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErroresValidacionVIEJOOperationCompleted);
            }
            this.InvokeAsync("GetErroresValidacionVIEJO", new object[] {
                        idTrans}, this.GetErroresValidacionVIEJOOperationCompleted, userState);
        }
        
        private void OnGetErroresValidacionVIEJOOperationCompleted(object arg) {
            if ((this.GetErroresValidacionVIEJOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErroresValidacionVIEJOCompleted(this, new GetErroresValidacionVIEJOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cesion.org/")]
    public partial class Parametro {
        
        private string codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cesion.org/")]
    public partial class InfoCuotas {
        
        private long providerRucField;
        
        private string seriesField;
        
        private int numerationField;
        
        private int numberField;
        
        private decimal netAmountField;
        
        private System.DateTime paymentDateField;
        
        /// <remarks/>
        public long providerRuc {
            get {
                return this.providerRucField;
            }
            set {
                this.providerRucField = value;
            }
        }
        
        /// <remarks/>
        public string series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        public int numeration {
            get {
                return this.numerationField;
            }
            set {
                this.numerationField = value;
            }
        }
        
        /// <remarks/>
        public int number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public decimal netAmount {
            get {
                return this.netAmountField;
            }
            set {
                this.netAmountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime paymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cesion.org/")]
    public partial class InfoFacturas {
        
        private long providerRucField;
        
        private string seriesField;
        
        private long numerationField;
        
        private string authorizationNumberField;
        
        private string invoiceTypeField;
        
        private System.DateTime expirationDateField;
        
        private string departmentField;
        
        private string provinceField;
        
        private string districtField;
        
        private string addressSupplierField;
        
        private string acqDepartmentField;
        
        private string acqProvinceField;
        
        private string acqDistrictField;
        
        private string addressAcquirerField;
        
        private int typePaymentField;
        
        private int numberQuotaField;
        
        private System.DateTime deliverDateAcqField;
        
        private System.DateTime aceptedDateField;
        
        private System.DateTime paymentDateField;
        
        private decimal netAmountField;
        
        private string other1Field;
        
        private string other2Field;
        
        private string additionalField1Field;
        
        private string additionalField2Field;
        
        /// <remarks/>
        public long providerRuc {
            get {
                return this.providerRucField;
            }
            set {
                this.providerRucField = value;
            }
        }
        
        /// <remarks/>
        public string series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        public long numeration {
            get {
                return this.numerationField;
            }
            set {
                this.numerationField = value;
            }
        }
        
        /// <remarks/>
        public string authorizationNumber {
            get {
                return this.authorizationNumberField;
            }
            set {
                this.authorizationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string invoiceType {
            get {
                return this.invoiceTypeField;
            }
            set {
                this.invoiceTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public string addressSupplier {
            get {
                return this.addressSupplierField;
            }
            set {
                this.addressSupplierField = value;
            }
        }
        
        /// <remarks/>
        public string acqDepartment {
            get {
                return this.acqDepartmentField;
            }
            set {
                this.acqDepartmentField = value;
            }
        }
        
        /// <remarks/>
        public string acqProvince {
            get {
                return this.acqProvinceField;
            }
            set {
                this.acqProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string acqDistrict {
            get {
                return this.acqDistrictField;
            }
            set {
                this.acqDistrictField = value;
            }
        }
        
        /// <remarks/>
        public string addressAcquirer {
            get {
                return this.addressAcquirerField;
            }
            set {
                this.addressAcquirerField = value;
            }
        }
        
        /// <remarks/>
        public int typePayment {
            get {
                return this.typePaymentField;
            }
            set {
                this.typePaymentField = value;
            }
        }
        
        /// <remarks/>
        public int numberQuota {
            get {
                return this.numberQuotaField;
            }
            set {
                this.numberQuotaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime deliverDateAcq {
            get {
                return this.deliverDateAcqField;
            }
            set {
                this.deliverDateAcqField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime aceptedDate {
            get {
                return this.aceptedDateField;
            }
            set {
                this.aceptedDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime paymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        public decimal netAmount {
            get {
                return this.netAmountField;
            }
            set {
                this.netAmountField = value;
            }
        }
        
        /// <remarks/>
        public string other1 {
            get {
                return this.other1Field;
            }
            set {
                this.other1Field = value;
            }
        }
        
        /// <remarks/>
        public string other2 {
            get {
                return this.other2Field;
            }
            set {
                this.other2Field = value;
            }
        }
        
        /// <remarks/>
        public string additionalField1 {
            get {
                return this.additionalField1Field;
            }
            set {
                this.additionalField1Field = value;
            }
        }
        
        /// <remarks/>
        public string additionalField2 {
            get {
                return this.additionalField2Field;
            }
            set {
                this.additionalField2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetTipoParticipanteCompletedEventHandler(object sender, GetTipoParticipanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTipoParticipanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTipoParticipanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Parametro[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Parametro[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GuardarInfoAdiccionalCompletedEventHandler(object sender, GuardarInfoAdiccionalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarInfoAdiccionalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarInfoAdiccionalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GuardarContenidoExcelCompletedEventHandler(object sender, GuardarContenidoExcelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarContenidoExcelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarContenidoExcelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ValidarExcelBDCompletedEventHandler(object sender, ValidarExcelBDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarExcelBDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarExcelBDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetErroresValidacionCompletedEventHandler(object sender, GetErroresValidacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErroresValidacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErroresValidacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GuardarInfoAdiccional2CompletedEventHandler(object sender, GuardarInfoAdiccional2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarInfoAdiccional2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarInfoAdiccional2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetInfoAdiccionalFacturasCompletedEventHandler(object sender, GetInfoAdiccionalFacturasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoAdiccionalFacturasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoAdiccionalFacturasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetInfoAdiccionalCuotasCompletedEventHandler(object sender, GetInfoAdiccionalCuotasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoAdiccionalCuotasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoAdiccionalCuotasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void VaciarTablasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetErroresValidacionVIEJOCompletedEventHandler(object sender, GetErroresValidacionVIEJOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErroresValidacionVIEJOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErroresValidacionVIEJOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591