//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WEB_CLIENTE.InterfazCavali.InputService04003 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_Dim_04003_Registrar_inf_adicionalSoap", Namespace="http://cesion/")]
    public partial class WS_Dim_04003_Registrar_inf_adicional : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegistrarInfoAdicionalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_Dim_04003_Registrar_inf_adicional() {
            this.Url = global::WEB_CLIENTE.Properties.Settings.Default.WEB_CLIENTE_WS_04003_WS_Dim_04003_Registrar_inf_adicional;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegistrarInfoAdicionalCompletedEventHandler RegistrarInfoAdicionalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cesion/RegistrarInfoAdicional", RequestNamespace="http://cesion/", ResponseNamespace="http://cesion/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MENSAJERES_Type RegistrarInfoAdicional(CABECERA_Type cabecera, Consumer_Type consumidor, InvoiceInformationAdditional_Type[] invoice, string usuario) {
            object[] results = this.Invoke("RegistrarInfoAdicional", new object[] {
                        cabecera,
                        consumidor,
                        invoice,
                        usuario});
            return ((MENSAJERES_Type)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarInfoAdicionalAsync(CABECERA_Type cabecera, Consumer_Type consumidor, InvoiceInformationAdditional_Type[] invoice, string usuario) {
            this.RegistrarInfoAdicionalAsync(cabecera, consumidor, invoice, usuario, null);
        }
        
        /// <remarks/>
        public void RegistrarInfoAdicionalAsync(CABECERA_Type cabecera, Consumer_Type consumidor, InvoiceInformationAdditional_Type[] invoice, string usuario, object userState) {
            if ((this.RegistrarInfoAdicionalOperationCompleted == null)) {
                this.RegistrarInfoAdicionalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarInfoAdicionalOperationCompleted);
            }
            this.InvokeAsync("RegistrarInfoAdicional", new object[] {
                        cabecera,
                        consumidor,
                        invoice,
                        usuario}, this.RegistrarInfoAdicionalOperationCompleted, userState);
        }
        
        private void OnRegistrarInfoAdicionalOperationCompleted(object arg) {
            if ((this.RegistrarInfoAdicionalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarInfoAdicionalCompleted(this, new RegistrarInfoAdicionalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb")]
    public partial class CABECERA_Type {
        
        private string cOD_SERVICIOField;
        
        private string aPP_CONSUMIDORAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_SERVICIO {
            get {
                return this.cOD_SERVICIOField;
            }
            set {
                this.cOD_SERVICIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string APP_CONSUMIDORA {
            get {
                return this.aPP_CONSUMIDORAField;
            }
            set {
                this.aPP_CONSUMIDORAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04003")]
    public partial class AddInvoiceInformationResponseDetail_Type {
        
        private string idProcesoField;
        
        private string resultCodeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string idProceso {
            get {
                return this.idProcesoField;
            }
            set {
                this.idProcesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04003")]
    public partial class AddInvoiceInformationResponse_Type {
        
        private AddInvoiceInformationResponseDetail_Type addInvoiceInformationResponseDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AddInvoiceInformationResponseDetail_Type addInvoiceInformationResponseDetail {
            get {
                return this.addInvoiceInformationResponseDetailField;
            }
            set {
                this.addInvoiceInformationResponseDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04003")]
    public partial class DATOSRes_Type {
        
        private AddInvoiceInformationResponse_Type addInvoiceInformationResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AddInvoiceInformationResponse_Type addInvoiceInformationResponse {
            get {
                return this.addInvoiceInformationResponseField;
            }
            set {
                this.addInvoiceInformationResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04003")]
    public partial class DETALLERes_Type {
        
        private DATOSRes_Type dATOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DATOSRes_Type DATOS {
            get {
                return this.dATOSField;
            }
            set {
                this.dATOSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb")]
    public partial class CABECERARes_Type {
        
        private string cOD_SERVICIOField;
        
        private string aPP_CONSUMIDORAField;
        
        private string tIP_RESPUESTAField;
        
        private string cOD_RESPUESTAField;
        
        private string dES_RESPUESTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_SERVICIO {
            get {
                return this.cOD_SERVICIOField;
            }
            set {
                this.cOD_SERVICIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string APP_CONSUMIDORA {
            get {
                return this.aPP_CONSUMIDORAField;
            }
            set {
                this.aPP_CONSUMIDORAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIP_RESPUESTA {
            get {
                return this.tIP_RESPUESTAField;
            }
            set {
                this.tIP_RESPUESTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_RESPUESTA {
            get {
                return this.cOD_RESPUESTAField;
            }
            set {
                this.cOD_RESPUESTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DES_RESPUESTA {
            get {
                return this.dES_RESPUESTAField;
            }
            set {
                this.dES_RESPUESTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04003")]
    public partial class INTEGRACIONRES_Type {
        
        private CABECERARes_Type cABECERAField;
        
        private DETALLERes_Type dETALLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CABECERARes_Type CABECERA {
            get {
                return this.cABECERAField;
            }
            set {
                this.cABECERAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DETALLERes_Type DETALLE {
            get {
                return this.dETALLEField;
            }
            set {
                this.dETALLEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04003")]
    public partial class MENSAJERES_Type {
        
        private INTEGRACIONRES_Type iNTEGRESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public INTEGRACIONRES_Type INTEGRES {
            get {
                return this.iNTEGRESField;
            }
            set {
                this.iNTEGRESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04003")]
    public partial class Payment_Type {
        
        private string numberField;
        
        private decimal netAmountField;
        
        private string paymentDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal netAmount {
            get {
                return this.netAmountField;
            }
            set {
                this.netAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04003")]
    public partial class InvoiceCode_Type {
        
        private string providerRucField;
        
        private string seriesField;
        
        private string numerationField;
        
        private string authorizationNumberField;
        
        private string invoiceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string providerRuc {
            get {
                return this.providerRucField;
            }
            set {
                this.providerRucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string numeration {
            get {
                return this.numerationField;
            }
            set {
                this.numerationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authorizationNumber {
            get {
                return this.authorizationNumberField;
            }
            set {
                this.authorizationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string invoiceType {
            get {
                return this.invoiceTypeField;
            }
            set {
                this.invoiceTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04003")]
    public partial class InvoiceInformationAdditional_Type {
        
        private InvoiceCode_Type invoiceCodeField;
        
        private string expirationDateField;
        
        private string departmentField;
        
        private string provinceField;
        
        private string districtField;
        
        private string addressSupplierField;
        
        private string acqDepartmentField;
        
        private string acqProvinceField;
        
        private string acqDistrictField;
        
        private string addressAcquirerField;
        
        private string typePaymentField;
        
        private string numberQuotaField;
        
        private string deliverDateAcqField;
        
        private string aceptedDateField;
        
        private string paymentDateField;
        
        private decimal netAmountField;
        
        private string other1Field;
        
        private string other2Field;
        
        private Payment_Type[] paymentDetailField;
        
        private string additionalField1Field;
        
        private string additionalField2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InvoiceCode_Type invoiceCode {
            get {
                return this.invoiceCodeField;
            }
            set {
                this.invoiceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addressSupplier {
            get {
                return this.addressSupplierField;
            }
            set {
                this.addressSupplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acqDepartment {
            get {
                return this.acqDepartmentField;
            }
            set {
                this.acqDepartmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acqProvince {
            get {
                return this.acqProvinceField;
            }
            set {
                this.acqProvinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acqDistrict {
            get {
                return this.acqDistrictField;
            }
            set {
                this.acqDistrictField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addressAcquirer {
            get {
                return this.addressAcquirerField;
            }
            set {
                this.addressAcquirerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string typePayment {
            get {
                return this.typePaymentField;
            }
            set {
                this.typePaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string numberQuota {
            get {
                return this.numberQuotaField;
            }
            set {
                this.numberQuotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deliverDateAcq {
            get {
                return this.deliverDateAcqField;
            }
            set {
                this.deliverDateAcqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aceptedDate {
            get {
                return this.aceptedDateField;
            }
            set {
                this.aceptedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal netAmount {
            get {
                return this.netAmountField;
            }
            set {
                this.netAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string other1 {
            get {
                return this.other1Field;
            }
            set {
                this.other1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string other2 {
            get {
                return this.other2Field;
            }
            set {
                this.other2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("payment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Payment_Type[] paymentDetail {
            get {
                return this.paymentDetailField;
            }
            set {
                this.paymentDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string additionalField1 {
            get {
                return this.additionalField1Field;
            }
            set {
                this.additionalField1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string additionalField2 {
            get {
                return this.additionalField2Field;
            }
            set {
                this.additionalField2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04003")]
    public partial class Consumer_Type {
        
        private string typeField;
        
        private string participantCodeField;
        
        private string rucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string participantCode {
            get {
                return this.participantCodeField;
            }
            set {
                this.participantCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void RegistrarInfoAdicionalCompletedEventHandler(object sender, RegistrarInfoAdicionalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarInfoAdicionalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarInfoAdicionalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MENSAJERES_Type Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MENSAJERES_Type)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591